import { NgModule } from '@angular/core';
import { IonicApp, IonicModule } from 'ionic-angular';
import { MyApp } from './app.component';
import { AngularFireModule } from 'angularfire2';

import { IonicStorageModule } from '@ionic/storage';

// diretives and providers
import { Loader } from '../providers/loader';
import { Nl2br } from '../pipes/nl2br';
import { HoursMinutesSeconds } from '../pipes/hours-minutes-seconds';
import { AuthenticatorService } from '../providers/authenticator';
import { Categories } from '../providers/categories';
import { Ionic2Rating } from 'ionic2-rating';

// Custom pages generated by ionic generator
import { HomePage } from '../pages/home/home';
import { SettingsPage } from '../pages/settings/settings';
import { ShoppingListPage } from '../pages/shopping-list/shopping-list';
import { TabsPage } from '../pages/tabs/tabs';
import { SearchPage } from '../pages/search/search';
import { DetailsPage } from '../pages/details/details';
import { CategoryPage } from '../pages/category/category';
import { IntroPage } from '../pages/intro/intro';

// Authentication
import { LoginPage } from '../pages/authentication/login/login';
import { RegistrationPage } from '../pages/authentication/registration/registration';

import { Config } from './config'

@NgModule({
  declarations: [
    MyApp,
    HomePage,
    TabsPage,
    SearchPage,
    ShoppingListPage,
    DetailsPage,
    CategoryPage,
    SettingsPage,
    LoginPage,
    RegistrationPage,
    Nl2br,
    HoursMinutesSeconds,
    Ionic2Rating,
    IntroPage
  ],
  imports: [
    IonicModule.forRoot(MyApp),
    IonicStorageModule.forRoot(),
    AngularFireModule.initializeApp(Config.FIREBASE_CONFIG)
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
    HomePage,
    TabsPage,
    SearchPage,
    ShoppingListPage,
    CategoryPage,
    DetailsPage,
    LoginPage,
    RegistrationPage,
    SettingsPage,
    IntroPage
  ],
  providers: [
    Loader,
    AuthenticatorService,
    Categories
  ]
})
export class AppModule {}
